name: Create Release

on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Version'
        required: true
      changelog:
        description: 'Change Log'
        required: false
        default: 'New version release'
jobs:
  createrelease:    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set Git Details
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com

      - name: Create Release Branch
        run: git checkout -b release/v${{ github.event.inputs.versionName }}
        
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: npm install
        
      - name: Build Project
        run: tsc
        
      - name: Commit changes
        run: |
          git add package.json
          git add src/*
          git commit -m 'New release for version "${{ github.event.inputs.versionName }}"'
          
      - name: Push New Release
        run: git push origin release/v${{ github.event.inputs.versionName }}
      
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name:  ${{ github.event.inputs.versionName }}
          release_name: v${{ github.event.inputs.versionName }}
          draft: false
          prerelease: false
